version: "3.7"
services:
    mariadb:
      image: jupyter/pyspark-notebook
      container_name: pyspark-notebook
      volumes:
        - ./volume/datasets:/home/jovyan/work/datasets
        - ./volume/notebooks:/home/jovyan/work/notebooks
      # env_file:
      #   - ./
      restart: always
      ports:
        - 8888:8888
        - 4040:4040
        - 4041:4041
        - 4042:4042
      networks:
        - internal


networks:
  internal:
    name: jupyterNetwork
    driver: bridge


volumes:
  notebook_data:
